### ISSUE TITLE
HOW CAN WE HAVE AN OLD 2015 CODE

### ISSUE THREAD

**Issue by pranavmathur** [Thunderbots-5604/2015-Code_OLD#3]
IF WE HAVENT WRITTEN  ANY CODE

DELETE THIS

**Comment by pranavmathur** [comment]
@ZachOhara @danielgrimshaw

**Comment by ZachOhara** [comment]
look at readme

**Comment by danielgrimshaw** [comment]
Don't delete this, this is the actual 2015-code. Delete 2015-code.

**Comment by pranavmathur** [comment]
Which should I write code on Right Now?

**Comment by danielgrimshaw** [comment]
2015-code_OLD

**Comment by ZachOhara** [comment]
Write code on the fork, called "2015-code", as oppsed to 2015-code_old.

**Comment by danielgrimshaw** [comment]
write to _OLD.

**Comment by ZachOhara** [comment]
Please copy all your changes to the new repo, or else I will. There are much more changes unique to the new one than to this repo, so that's the easiest way to align the codebase. Then we can decide what to do from there.
